# TensorFlow basic syntax 

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.12.0'

In [11]:
hello = tf.constant('Hello ')
world = tf.constant('World')

In [12]:
type(world)

tensorflow.python.framework.ops.Tensor

In [13]:
hello

<tf.Tensor 'Const_3:0' shape=() dtype=string>

In [14]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [15]:
result

b'Hello World'

In [16]:
a = tf.constant(10)
b = tf.constant(20)

In [17]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [19]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [20]:
result

30

In [22]:
const = tf.constant(10)
fill_mat = tf.fill((4, 4), 10)
my_zeros = tf.zeros((4, 4))
my_ones = tf.ones((4, 4))
my_randn = tf.random_normal((4, 4))
my_randu = tf.random_uniform((4, 4), maxval=1)

In [24]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

In [25]:
sess = tf.InteractiveSession()

In [27]:
for operation in my_ops:
    print(sess.run(operation), '\n')

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[ 0.7803506  -0.12209307 -0.67654914 -0.21101351]
 [ 0.55707216 -0.00533562 -2.0048263  -1.0137678 ]
 [ 0.32855803 -0.8430732   0.6985942  -1.1891373 ]
 [-1.174727    1.2753688  -1.2074882   0.38342643]] 

[[0.72070885 0.20576966 0.98622274 0.7119571 ]
 [0.85866475 0.877614   0.5240232  0.20821881]
 [0.76165354 0.73010564 0.4750173  0.6855998 ]
 [0.4692495  0.5035138  0.003739   0.7861074 ]] 



In [31]:
a = tf.constant([[1, 2], [3, 4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [32]:
b = tf.constant([[10], [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
sess.run(tf.matmul(a, b))

array([[210],
       [430]], dtype=int32)